### ISSUE TITLE
Training System Master Issue

### ISSUE THREAD

**Issue by andrewogden1678** [czqoocavatsim/czqo-core#82]
### Functional Requirements
- [x] Revised applications system with referee integration** and automatically adding new students to the 'to be processed' list
- [ ] Chief Instructor can assign students to instructors
- [ ] Instructors can view student profiles, where they can leave session notes and view the student's email address
- [ ] Students can book training sessions with their instructor (and the other way around) through a calendar interface
- [ ] Students can be marked 'Recommended for Assessment'
- [ ] Students can be marked as certified, or have their training cancelled (upon cancel, remove from system)
- [ ] OTS records can be entered into a student profile
- [ ] Instructors can be edited, and can be upgraded to Assessor (permission to add OTS records and mark students as certified
- [ ] Roster can be directly edited, marking individuals as inactive or even removing individuals entirely from the roster
- [ ] Can click 'Mark inactive controllers' at each activity point, similar button to 'Mark removal'

** *See issue https://github.com/gander-oceanic-fir-vatsim/czqo-core/issues/27*

**See also:**
- [ ] Applications: Issue https://github.com/gander-oceanic-fir-vatsim/czqo-core/issues/37
- [ ] Roster: Issue https://github.com/gander-oceanic-fir-vatsim/czqo-core/issues/38
- [ ] Permissions: Issue https://github.com/gander-oceanic-fir-vatsim/czqo-core/issues/71
- [ ] Users: Issue https://github.com/gander-oceanic-fir-vatsim/czqo-core/issues/70

**Comment by andrewogden1678** [comment]
- [ ] Ability to upload and display (embed) OTS reports for a student. A 'view by student' and 'view all' would be good, sorting by date added.
